// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNgovQzj6d0TOj605cX21OaZ60y8_IDZU',
    appId: '1:550067676415:web:0ae5263ae497fe354d18ca',
    messagingSenderId: '550067676415',
    projectId: 'mystore-d2838',
    authDomain: 'mystore-d2838.firebaseapp.com',
    storageBucket: 'mystore-d2838.firebasestorage.app',
    measurementId: 'G-5Y30LD9KLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDISwoGCgt9haftmrcNCpS4P9qgvjm4FuM',
    appId: '1:550067676415:android:ff4eb6edda4afb554d18ca',
    messagingSenderId: '550067676415',
    projectId: 'mystore-d2838',
    storageBucket: 'mystore-d2838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQ3rSG5p0k92SZuHdoHI9F8Zie7hR6VU',
    appId: '1:550067676415:ios:e19877323180054b4d18ca',
    messagingSenderId: '550067676415',
    projectId: 'mystore-d2838',
    storageBucket: 'mystore-d2838.firebasestorage.app',
    iosBundleId: 'com.example.mystore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXQ3rSG5p0k92SZuHdoHI9F8Zie7hR6VU',
    appId: '1:550067676415:ios:e19877323180054b4d18ca',
    messagingSenderId: '550067676415',
    projectId: 'mystore-d2838',
    storageBucket: 'mystore-d2838.firebasestorage.app',
    iosBundleId: 'com.example.mystore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNgovQzj6d0TOj605cX21OaZ60y8_IDZU',
    appId: '1:550067676415:web:b43e496bb02d15424d18ca',
    messagingSenderId: '550067676415',
    projectId: 'mystore-d2838',
    authDomain: 'mystore-d2838.firebaseapp.com',
    storageBucket: 'mystore-d2838.firebasestorage.app',
    measurementId: 'G-009V713TNF',
  );
}
